application: django-snippets
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: django_snippets/static
 
- url: /search_the_web/static
  static_dir: django_snippets/search_the_web/static
 
- url: /jpycal/static
  static_dir: django_snippets/jpycal/static
 
- url: .*
  script: django_snippets/gae.py
